{$i AlwaysInclude.inc}

unit NLResourceStrings;

// Use deze unit in je project als je alle RTL/VCL resource strings vertaald wilt hebben in het Nederlands.

interface

implementation

uses
  NLConsts, NLRTLConsts, NLSysConst;

(*
// untranslated
Consts.SOpenFileTitle - untranslated: English = "Open"
Consts.SInvalidTabPosition - untranslated: English = "Tab position incompatible with current tab style"
Consts.SInvalidTabStyle - untranslated: English = "Tab style incompatible with current tab position"
Consts.SOKButton - untranslated: English = "OK"
Consts.SHelpButton - untranslated: English = "&Help"
Consts.SFB - untranslated: English = "FB"
Consts.SFG - untranslated: English = "FG"
Consts.SBG - untranslated: English = "BG"
Consts.SVMetafiles - untranslated: English = "Metafiles"
Consts.SVEnhMetafiles - untranslated: English = "Enhanced Metafiles"
Consts.SVBitmaps - untranslated: English = "Bitmaps"
Consts.SMsgDlgOK - untranslated: English = "OK"
Consts.SMsgDlgHelp - untranslated: English = "&Help"
Consts.SMsgDlgHelpHelp - untranslated: English = "Help"
Consts.SmkcBkSp - untranslated: English = "BkSp"
Consts.SmkcTab - untranslated: English = "Tab"
Consts.SmkcEsc - untranslated: English = "Esc"
Consts.SmkcEnter - untranslated: English = "Enter"
Consts.SmkcSpace - untranslated: English = "Space"
Consts.SmkcPgUp - untranslated: English = "PgUp"
Consts.SmkcPgDn - untranslated: English = "PgDn"
Consts.SmkcEnd - untranslated: English = "End"
Consts.SmkcHome - untranslated: English = "Home"
Consts.SmkcLeft - untranslated: English = "Left"
Consts.SmkcUp - untranslated: English = "Up"
Consts.SmkcRight - untranslated: English = "Right"
Consts.SmkcDown - untranslated: English = "Down"
Consts.SmkcIns - untranslated: English = "Ins"
Consts.SmkcDel - untranslated: English = "Del"
Consts.SmkcShift - untranslated: English = "Shift+"
Consts.SmkcCtrl - untranslated: English = "Ctrl+"
Consts.SmkcAlt - untranslated: English = "Alt+"
Consts.SColorTags - untranslated: English = "ABCDEFGHIJKLMNOP"
Consts.SCannotOpenClipboard - untranslated: English = "Cannot open clipboard"
Consts.SPictureLabel - untranslated: English = "Picture:"
Consts.SPictureDesc - untranslated: English = " (%dx%d)"
Consts.SPreviewLabel - untranslated: English = "Preview"
Consts.SCannotOpenAVI - untranslated: English = "Cannot open AVI"
Consts.SNotOpenErr - untranslated: English = "No MCI device open"
Consts.SMCINil - untranslated: English = ""
Consts.SMCIAVIVideo - untranslated: English = "AVIVideo"
Consts.SMCICDAudio - untranslated: English = "CDAudio"
Consts.SMCIDAT - untranslated: English = "DAT"
Consts.SMCIDigitalVideo - untranslated: English = "DigitalVideo"
Consts.SMCIMMMovie - untranslated: English = "MMMovie"
Consts.SMCIOther - untranslated: English = "Other"
Consts.SMCIOverlay - untranslated: English = "Overlay"
Consts.SMCIScanner - untranslated: English = "Scanner"
Consts.SMCISequencer - untranslated: English = "Sequencer"
Consts.SMCIVCR - untranslated: English = "VCR"
Consts.SMCIVideodisc - untranslated: English = "Videodisc"
Consts.SMCIWaveAudio - untranslated: English = "WaveAudio"
Consts.SMCIUnknownError - untranslated: English = "Unknown error code"
Consts.SBoldItalicFont - untranslated: English = "Bold Italic"
Consts.SBoldFont - untranslated: English = "Bold"
Consts.SItalicFont - untranslated: English = "Italic"
Consts.SRegularFont - untranslated: English = "Regular"
Consts.SPropertiesVerb - untranslated: English = "Properties"
Consts.SServiceFailed - untranslated: English = "Service failed on %s: %s"
Consts.SExecute - untranslated: English = "execute"
Consts.SStart - untranslated: English = "start"
Consts.SStop - untranslated: English = "stop"
Consts.SPause - untranslated: English = "pause"
Consts.SContinue - untranslated: English = "continue"
Consts.SInterrogate - untranslated: English = "interrogate"
Consts.SShutdown - untranslated: English = "shutdown"
Consts.SCustomError - untranslated: English = "Service failed in custom message(%d): %s"
Consts.SServiceInstallOK - untranslated: English = "Service installed successfully"
Consts.SServiceInstallFailed - untranslated: English = "Service "%s" failed to install with error: "%s""
Consts.SServiceUninstallOK - untranslated: English = "Service uninstalled successfully"
Consts.SServiceUninstallFailed - untranslated: English = "Service "%s" failed to uninstall with error: "%s""
Consts.SInvalidActionRegistration - untranslated: English = "Invalid action registration"
Consts.SInvalidActionUnregistration - untranslated: English = "Invalid action unregistration"
Consts.SInvalidActionEnumeration - untranslated: English = "Invalid action enumeration"
Consts.SInvalidActionCreation - untranslated: English = "Invalid action creation"
Consts.SDockedCtlNeedsName - untranslated: English = "Docked control must have a name"
Consts.SDockTreeRemoveError - untranslated: English = "Error removing control from dock tree"
Consts.SDockZoneNotFound - untranslated: English = " - Dock zone not found"
Consts.SDockZoneHasNoCtl - untranslated: English = " - Dock zone has no control"
Consts.SAllCommands - untranslated: English = "All Commands"
Consts.SDuplicateItem - untranslated: English = "List does not allow duplicates ($0%x)"
RTLConsts.SDuplicateItem - untranslated: English = "List does not allow duplicates ($0%x)"
RTLConsts.SInvalidActionCreation - untranslated: English = "Invalid action creation"
RTLConsts.SInvalidActionEnumeration - untranslated: English = "Invalid action enumeration"
RTLConsts.SInvalidActionRegistration - untranslated: English = "Invalid action registration"
RTLConsts.SInvalidActionUnregistration - untranslated: English = "Invalid action unregistration"
RTLConsts.SInvalidMask - untranslated: English = "'%s' is an invalid mask at (%d)"
RTLConsts.SInvalidPropertyElement - untranslated: English = "Invalid property element: %s"
RTLConsts.SInvalidPropertyType - untranslated: English = "Invalid property type: %s"
RTLConsts.sWindowsSocketError - untranslated: English = "Windows socket error: %s (%d), on API '%s'"
RTLConsts.sAsyncSocketError - untranslated: English = "Asynchronous socket error %d"
RTLConsts.sNoAddress - untranslated: English = "No address specified"
RTLConsts.sCannotListenOnOpen - untranslated: English = "Can't listen on an open socket"
RTLConsts.sCannotCreateSocket - untranslated: English = "Can't create new socket"
RTLConsts.sSocketAlreadyOpen - untranslated: English = "Socket already open"
RTLConsts.sCantChangeWhileActive - untranslated: English = "Can't change value while socket is active"
RTLConsts.sSocketMustBeBlocking - untranslated: English = "Socket must be in blocking mode"
RTLConsts.sSocketIOError - untranslated: English = "%s error %d, %s"
RTLConsts.sSocketRead - untranslated: English = "Read"
RTLConsts.sSocketWrite - untranslated: English = "Write"
*)
end.
