unit TestNullableTypes;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Variants, NullableTypes, SysUtils;

type
  // Test methods for class NullabeType

  TestNullableType = class(TTestCase)
  strict private

  published
    procedure TestAddInt;
    procedure TestAddNull;
  end;

implementation

{ TestNullableType }

procedure TestNullableType.TestAddInt;
var
  n1, n2: Nullable<integer>;
begin
  n1 := 1;
  n2 := 3;
  CheckEquals(4, n1 + n2);

end;

procedure TestNullableType.TestAddNull;
var
  n1, n2, n3: Nullable<integer>;
begin
  n1 := 1;
  n2.ClearValue;
  n3 := n1 + n2;
  CheckTrue(n3.IsNull);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestNullableType.Suite);
end.

